### PR TITLE
Revise DevelopmentSetup.md

### PR DESCRIPTION
**Pull request by abebeos**
Test section belongs into the dev-setup.
Simplify dev-setup document via minor revisions.

(This needs multiple more passes. Note that this is  a process that takes some time.)

### CODE REVIEW

**Comment by abebeos** [comment]
I start to get the impression that this document is about "DevelopmentSetup" for dapp developers (I think "builders", in jargon).

Is this correct? Or does it apply additionally to core-developers (that develop on Bifrost itself) ?

**Review by SeanCheatham — APPROVED** [review]
@abebeos Thanks again for your contribution!
> I start to get the impression that this document is about "DevelopmentSetup" for dapp developers (I think "builders", in jargon).
> 
> Is this correct? Or does it apply additionally to core-developers (that develop on Bifrost itself) ?

The DevelopmentSetup.md instructions apply to core protocol developers.  dApp developers will likely follow similar instructions if using BramblSc, but we haven't formalized that process yet.

**Comment by abebeos** [comment]
> The DevelopmentSetup.md instructions apply to core protocol developers.

Very well, then my additions to fork and add upstream are valid.

**Comment by abebeos** [comment]
@SeanCheatham I shred my github-account now and then. You should be able to reopen and merge.

**Pull request closed without merging**
