### PR TITLE
Int128 Integral Typeclass

### LINKED ISSUE #1121: Create Ordering[Int128] and Numeric[Int128] TypeClasses
Scala collections offer methods like `.sum` which adds up all numbers in a collection and `.sort` which sorts items in a collection.  These operations leverage implicit typeclasses `Numeric` and `Ordering` to do this work.  The standard Scala numbers all have corresponding type classes.  We should do the same for the new `Int128` class.

i.e.
```scala
object Int128 {

    implicit val numericInt128: Numeric[Int128] = new Numeric[Int128] {
        ...
    }

    implicit val orderingInt128: Ordering[Int128] = new Ordering[Int128] {
        ...
    }
}
```

```scala
import Int128._
List(Int128(0)).sum
```

Acceptance Criteria:
- A Numeric typeclass exists for Int128
- An Ordering typeclass exists for Int128
- A collection of Int128s can be sorted or summed

### PR DESCRIPTION
**Pull request by SeanCheatham**
## Purpose
- Certain Scala operations, such as sorting or summing collections, leverage a TypeClass pattern
- Int128 can be viewed as `scala.math.Integral` which essentially means it is Numeric and Whole, so a typeclass can be created

## Approach
- Implemented Integral and Ordering traits for Int128
- Added an implicit object to Int128 extending both Integral and Ordering
- Refactored instances of `.foldLeft[Int128](0)(_ + _)` into `.sum`

## Testing
- Added Int128 generators
- Added basic Int128 test cases

## Tickets
- closes #1121

### CODE REVIEW

**Review by scasplte2 — APPROVED** [review]
👍 very nicely done @SeanCheatham. Since we're fairly new to typeclasses in general, please briefly go over this with everyone else and see if they have any questions. Afterwards, y'all can feel free to merge this in. 

I think this can also close #1029 unless you can think of additional tests you'd like to cover.

**Review by jingsting — APPROVED** [review]
🥏

**Review by jingsting — APPROVED** [review]
🛸

**Review by b-vennes — APPROVED** [review]
Looks great!

**Pull request merged**
