### PR TITLE
Tsdk 47 implement the genus block api part 1

### PR DESCRIPTION
**Pull request by nandotorterolo**
## Purpose

Sources:
- Implement: `rpc getBlockByDepth(GetBlockByDepthRequest) returns (BlockResponse);` [protobufSpec](https://github.com/Topl/protobuf-specs/blob/main/proto/genus/genus_rpc.proto#L37)
- Refactor: genusLibrary.orientDb package was split in 2 packages, Schema factory, and Schema Instances, developers should add new schemas on Instances packages, and not change schema factory
- Refactor Genus Exceptions (GE),  short names to avoid verbose code, extending Exception instead of RuntimeExceptions, the library itself  does not throw checked or unchecked exceptions, the server returns exceptions (runtime exceptions are experimental) 

Test:
- Add: Genus Server unit Test
- Add: Genus Library unit test, for `GraphVertexFetcher:fetchHeaderByDepth`
- Add: Genus Library unit test, for all `Genus Exceptions
- Add: Genus Library Schema metadata unit test for class `TestClass`, eventually a new test for each Schema should be created
 

## Testing
Given a current chain with 132 nodes
```console
fernando@fernando-um700:~/topl/GenusTest$ gwhisper localhost:9091 co.topl.genus.services.GenusFullBlockService getBlockByHeight height=:value=2: > height_2.txt
2023-03-27 08:27:06: Received message:
RPC succeeded :D
fernando@fernando-um700:~/topl/GenusTest$ gwhisper localhost:9091 co.topl.genus.services.GenusFullBlockService getBlockByDepth depth=:value=130: > depth_2.txt
2023-03-27 08:27:21: Received message:
RPC succeeded :D
fernando@fernando-um700:~/topl/GenusTest$ diff -s height_2.txt depth_2.txt 
Files height_2.txt and depth_2.txt are identical
fernando@fernando-um700:~/topl/GenusTest$ 

```

## Tickets
[TSDK-47](https://topl.atlassian.net/browse/TSDK-47)

[TSDK-47]: https://topl.atlassian.net/browse/TSDK-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by abebeos** [comment]
This is **very difficult** to review. Consider:

* use more commits, one for each logical step.
  * e.g. One commit for one search&replace,
  * one commit for each refactoring step
  * etc.
* if applicable, even split this into multiple PRs.

**Review by SeanCheatham — APPROVED** [review]
:brain:

**Comment by nandotorterolo** [comment]
> This is **very difficult** to review. Consider:
> 
> * use more commits, one for each logical step.
>   
>   * e.g. One commit for one search&replace,
>   * one commit for each refactoring step
>   * etc.
> * if applicable, even split this into multiple PRs.

Thanks, I will consider your suggestion in next PRs.

**Comment by abebeos** [comment]
> Thanks, I will consider your suggestion in next PRs.

Filed an issue, as this is general and belongs into the coredev manual. 

https://github.com/Topl/Bifrost/issues/2885

**Pull request merged**
