### PR TITLE
Updated the dataStringGen generator

### PR DESCRIPTION
**Pull request by jingsting**
## Summary
Fixed none.get error for dataStringGen generator

## Changes
- Updated the invalid data string generator so it will not trigger none.get errors

### CODE REVIEW

**Comment by scasplte2** [comment]
which ticket is this attached to @jingsting

**Comment by scasplte2** [comment]
Is this still applicable given #1483 @jingsting ?

**Comment by scasplte2** [comment]
@jing can you take a look at this conflict when you get a chance?

**Comment by jingsting** [comment]
@scasplte2 I tested running tests without the changes in this PR and with Sean's sampleFirst methods in dev the tests won't fail, so I'm closing this PR

**Pull request closed without merging**
